'use client';
import { Invoice, BusinessProfile, InvoiceSettings } from '@/lib/types';
import { useAuth } from '@/hooks/use-auth';
import { useEffect, useState } from 'react';
import { getBusinessProfile, getInvoiceSettings } from '@/lib/firestore';
import { Building } from 'lucide-react';

interface InvoicePDFViewProps {
  invoice: Invoice;
}

export function InvoicePDFView({ invoice }: InvoicePDFViewProps) {
    const { user } = useAuth();
    const [profile, setProfile] = useState<BusinessProfile | null>(null);
    const [settings, setSettings] = useState<InvoiceSettings | null>(null);
    
    useEffect(() => {
        if(user?.uid) {
            getBusinessProfile(user.uid).then(setProfile);
            getInvoiceSettings(user.uid).then(setSettings);
        }
    }, [user, invoice]);

  return (
    <div id={`invoice-pdf-view-${invoice.id}`} className="p-6 bg-white text-gray-800 font-sans text-sm" style={{width: '800px', margin: 'auto'}}>
        {/* Header */}
        <header className="flex justify-between items-start mb-6">
            <div className="company-info text-xs">
                {settings?.companyLogoUrl ? (
                    <img src={settings.companyLogoUrl} alt="Company Logo" className="w-20 h-auto mb-2" />
                ) : (
                    <div className="w-20 h-20 mb-2 bg-gray-100 flex items-center justify-center rounded">
                        <Building className="w-10 h-10 text-gray-400" />
                    </div>
                )}
                <h2 className="text-lg font-bold text-gray-900">{profile?.companyName || "Your Company"}</h2>
                <p>{profile?.businessAddress}</p>
                <p>Email: {profile?.businessEmail}</p>
                <p>Phone: {profile?.businessPhone}</p>
                {profile?.website && <p>Website: {profile.website}</p>}
                {profile?.taxNumber && <p>TAX/VAT No: {profile.taxNumber}</p>}
            </div>
            <div className="invoice-info text-right text-xs">
                <h1 className="text-3xl font-bold text-gray-900 mb-2">INVOICE</h1>
                <p><strong>Invoice #:</strong> {`${settings?.invoicePrefix || ''}${invoice.id.substring(0,6).toUpperCase()}`}</p>
                <p><strong>Date Issued:</strong> {new Date().toLocaleDateString()}</p>
                <p><strong>Due Date:</strong> {new Date(invoice.dueDate).toLocaleDateString()}</p>
            </div>
        </header>

        {/* Bill To */}
        <div className="bill-to my-5">
            <h3 className="text-base font-bold underline mb-1">BILL TO</h3>
            <p>{invoice.client?.name}</p>
            <p>{invoice.client?.email}</p>
            <p>{invoice.client?.phone}</p>
        </div>

        {/* Items Table */}
        <table className="w-full border-collapse mb-6">
            <thead>
                <tr>
                    <th className="bg-[#1D3557] text-white p-2.5 text-left">Description</th>
                    <th className="bg-[#1D3557] text-white p-2.5 text-left">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td className="p-2.5 border-b border-gray-300">Service/Product Rendered</td>
                    <td className="p-2.5 border-b border-gray-300">R {invoice.amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                </tr>
            </tbody>
        </table>

        {/* Total */}
        <div className="text-right mb-4">
            <h2 className="text-xl font-bold">Total: R {invoice.amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</h2>
        </div>
        
        {/* Payment Instructions */}
        <div className="text-sm italic my-2">
            <p>{settings?.paymentTerms || 'Please make payment within the specified due date.'}</p>
            <p>Use the invoice number as your payment reference.</p>
        </div>

        {/* Banking Details */}
        <div className="mt-6 border-t-2 border-gray-300 pt-2 text-sm">
            <h3 className="text-base font-bold mb-1">BANKING DETAILS</h3>
            <p><strong>Bank:</strong> {profile?.bankName}</p>
            <p><strong>Account Holder:</strong> {profile?.accountHolder}</p>
            <p><strong>Account Number:</strong> {profile?.accountNumber}</p>
            <p><strong>Branch Code:</strong> {profile?.branchCode}</p>
        </div>

        {/* Footer */}
        <p className="text-center text-gray-500 text-xs mt-8">
            Thank you for your business!
            <br />
            {settings?.showWatermark && `Generated by Dulus Business Manager © ${new Date().getFullYear()} Dulus Data Dynamics`}
        </p>
    </div>
  );
}
